{{- if .Values.query.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-query"
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
{{- end }}