{{- if .Values.query.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-query"
{{- end }}