{{- if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-query"
spec:
  replicas: {{ .Values.query.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-query
      app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
      {{- include "thanos.selectorlabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: thanos-query
        app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-query"
        {{- include "thanos.commonlabels" . | nindent 8 }}
    spec:
      {{- if .Values.query.affinity }}
      affinity: 
      {{- .Values.query.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.query.tolerations }}
      tolerations: 
      {{- .Values.query.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.query.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- .Values.query.topologySpreadConstraints | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{- include "thanos.fullname" . }}-query"
      containers:
      - args:
        {{- range $key, $value := .Values.query.args }}
        - {{ $value }}
        {{- end }}
        - --store=dnssrv+_grpc._tcp.{{- include "thanos.fullname" . }}-store:10901
        resources:
        {{- .Values.query.resources | toYaml | nindent 10 }}
        name: "{{- include "thanos.fullname" . }}-query"
        env:
        - name: HOST_IP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: "{{ .Values.global.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 10901
          name: grpc
          protocol: TCP
        - containerPort: 9090
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
{{- end }}