{{- if .Values.queryfrontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: thanos-queryfrontend
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-queryfrontend"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-queryfrontend"
{{- end }}