{{- if .Values.compactor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{ toYaml .Values.global.serviceAccount.annotations }}
  labels:
    app.kubernetes.io/component: thanos-compactor
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-compactor"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-compactor"
{{- end }}