{{- if .Values.compactor.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-compactor
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-compactor"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-compactor"
spec:
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app.kubernetes.io/component: thanos-compactor
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-compactor"
{{- end }}