{{- if .Values.store.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-store
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-store"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-store"
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app.kubernetes.io/component: thanos-store
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-store"
{{- end }}