{{- if .Values.store.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: thanos-store
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-store"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-store"
spec:
  endpoints:
  - port: http
    relabelings:
    - separator: /
      sourceLabels:
      - namespace
      - pod
      targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-store
      app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-store"
{{- end }}