{{- if .Values.store.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{ toYaml .Values.global.serviceAccount.annotations }}
  labels:
    app.kubernetes.io/component: thanos-store
    app.kubernetes.io/name: "{{- include "thanos.fullname" . }}-store"
    {{- include "thanos.commonlabels" . | nindent 4 }}
  name: "{{- include "thanos.fullname" . }}-store"
{{- end }}